#! /bin/bash

# Runs a repo-local ltsep wrapper so SIMC jobs do not depend on upstream
# getPathDict.py field ordering or os.getlogin() behavior on farm nodes.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
LTSEP_FIELDS_SCRIPT="${REPO_ROOT}/farm_env/print_ltsep_path_fields.py"
PATHFILE_INFO="$(python3 "${LTSEP_FIELDS_SCRIPT}" "${REPO_ROOT}")"
path_rc=$?
if [[ "${path_rc}" -ne 0 || -z "${PATHFILE_INFO}" ]]; then
    echo "ERROR: failed to resolve ltsep paths via ${LTSEP_FIELDS_SCRIPT}" >&2
    exit 1
fi

# Split the string we get to individual variables, easier for printing and use later
VOLATILEPATH=`echo ${PATHFILE_INFO} | cut -d ','  -f1` # Cut the string on , delimitter, select field (f) 1, set variable to output of command
ANALYSISPATH=`echo ${PATHFILE_INFO} | cut -d ','  -f2`
HCANAPATH=`echo ${PATHFILE_INFO} | cut -d ','  -f3`
REPLAYPATH=`echo ${PATHFILE_INFO} | cut -d ','  -f4`
UTILPATH=`echo ${PATHFILE_INFO} | cut -d ','  -f5`
PACKAGEPATH=`echo ${PATHFILE_INFO} | cut -d ','  -f6`
OUTPATH=`echo ${PATHFILE_INFO} | cut -d ','  -f7`
ROOTPATH=`echo ${PATHFILE_INFO} | cut -d ','  -f8`
SKIMPATH=`echo ${PATHFILE_INFO} | cut -d ','  -f9`
REPORTPATH=`echo ${PATHFILE_INFO} | cut -d ','  -f10`
CUTPATH=`echo ${PATHFILE_INFO} | cut -d ','  -f11`
PARAMPATH=`echo ${PATHFILE_INFO} | cut -d ','  -f12`
SCRIPTPATH=`echo ${PATHFILE_INFO} | cut -d ','  -f13`
ANATYPE=`echo ${PATHFILE_INFO} | cut -d ','  -f14`
USER=`echo ${PATHFILE_INFO} | cut -d ','  -f15`
HOST=`echo ${PATHFILE_INFO} | cut -d ','  -f16`
SIMCPATH=`echo ${PATHFILE_INFO} | cut -d ','  -f17`
LTANAPATH=`echo ${PATHFILE_INFO} | cut -d ','  -f18`

SIMC_RUNTIME_PATH="${SIMC_OVERRIDE_PATH:-${SIMCPATH}}"
SIMC_RUNTIME_LOG_DIR="${SIMC_LOG_DIR:-${LTANAPATH}/log}"

mkdir -p "${SIMC_RUNTIME_LOG_DIR}"

cd "${SIMC_RUNTIME_PATH}" || exit 1
if [[ -f /site/12gev_phys/softenv.sh ]]; then
    source /site/12gev_phys/softenv.sh 2.3
fi
if [[ -f /apps/root/6.22.06/setroot_CUE.bash ]]; then
    source /apps/root/6.22.06/setroot_CUE.bash
elif [[ -f /apps/root/6.18.04/setroot_CUE.bash ]]; then
    source /apps/root/6.18.04/setroot_CUE.bash
else
    echo "WARNING: no setroot_CUE.bash found under /apps/root; continuing with current ROOT environment" >&2
fi
make clean
make
./simc << endofinput 2> "${SIMC_RUNTIME_LOG_DIR}/$1.log"
$1
endofinput
cd "${SIMC_RUNTIME_PATH}/util/root_tree" || exit 1
make clean
make
./make_root_tree << endofinput
$1
endofinput
cd "${SIMC_RUNTIME_PATH}" || exit 1
mv "worksim/$1.root" OUTPUTS

REACTION=$2
echo "Reaction selected: $2" 
cd "${SIMC_RUNTIME_PATH}/recon_hcana" || exit 1
root -q -l "recon_hcana.C(\"$1\", \"$REACTION\" )"
